# # backend/main.py
# from flask import Flask, request, jsonify, send_from_directory
# from flask_cors import CORS
# from flask_compress import Compress
# import json
# import os
# import pandas as pd
# from datetime import datetime

# # Import db helper and model
# from db import read_sql, DATABASE_URL
# from models.classification import predict_water_quality, features as classification_features

# BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))

# # Paths
# LOCATIONS_CSV_PATH = os.path.join(BACKEND_DIR, "data/cpcb_station_locations.csv")
# STATIC_DIR = os.path.join(BACKEND_DIR, "static")
# DAILY_PRED_DIR = os.path.join(STATIC_DIR, "predictions/daily")
# WEEKLY_PRED_DIR = os.path.join(STATIC_DIR, "predictions/weekly")
# DAYNIGHT_DIR = os.path.join(STATIC_DIR, "daynight")
# ANOMALY_PLOT_PATH = os.path.join(STATIC_DIR, "anomaly/anomaly_heatmap.json")
# CORRELATION_DIR = os.path.join(STATIC_DIR, "correlation")
# WEEKLY_DETAILS_DIR = os.path.join(STATIC_DIR, "predictions/weekly_details")
# DAILY_SUMMARY_PATH = os.path.join(STATIC_DIR, "predictions/daily_summary_predictions.json")
# WEEKLY_SUMMARY_PATH = os.path.join(STATIC_DIR, "predictions/weekly_summary_predictions.json")
# STATION_QUALITY_PATH = os.path.join(STATIC_DIR, "station_quality.json")

# TABLE_NAME = "water_records"

# # Flask setup
# app = Flask(__name__, static_folder=STATIC_DIR)
# CORS(app, origins=[
#     "http://localhost:5173",
#     "http://localhost:3000",
#     "https://aqua-metrics32.vercel.app",
# ], supports_credentials=False)
# Compress(app)  # Gzip compression — makes JSON responses much faster


# # ─── Helper to read a JSON file safely ───────────────────────────────────────

# def read_json_file(path):
#     if not os.path.exists(path):
#         return None, f"File not found: {path}"
#     try:
#         with open(path, 'r') as f:
#             return json.load(f), None
#     except Exception as e:
#         return None, str(e)


# # ─── Station List ─────────────────────────────────────────────────────────────
# @app.route('/', methods=['GET'])
# def health_check():
#     return jsonify({"status": "ok", "message": "AquaMetrics backend is running"})

# @app.route('/api/stations', methods=['GET'])
# def get_stations():
#     """
#     Returns the list of stations with lat/lng and water quality label.
#     Quality is read from a pre-computed JSON file (generated by batch job).
#     Falls back to live classification if the file doesn't exist.
#     """
#     try:
#         locations_df = pd.read_csv(LOCATIONS_CSV_PATH)
#         locations_df = locations_df[['station_id', 'station_name', 'latitude', 'longitude', 'state']].rename(columns={
#             'station_id': 'stationId',
#             'station_name': 'name',
#             'latitude': 'lat',
#             'longitude': 'lng',
#             'state': 'location'
#         })
#         locations_df['stationId'] = locations_df['stationId'].astype(int)
#     except Exception as e:
#         print(f"ERROR loading locations CSV: {e}")
#         return jsonify({"error": "Failed to load station location data."}), 500

#     # Try to load pre-computed quality (fast path)
#     if os.path.exists(STATION_QUALITY_PATH):
#         try:
#             with open(STATION_QUALITY_PATH, 'r') as f:
#                 quality_map = json.load(f)  # { "stationId": "Good", ... }
#             locations_df['quality'] = locations_df['stationId'].astype(str).map(quality_map).fillna('Medium')
#             return jsonify(locations_df.to_dict('records'))
#         except Exception as e:
#             print(f"Warning: Could not read station_quality.json: {e}. Falling back to live classification.")

#     # Fallback: live classification (slow — only runs if batch job hasn't created the file yet)
#     try:
#         query = f"""
#         SELECT t1.* FROM {TABLE_NAME} t1
#         INNER JOIN (
#             SELECT "stationId", MAX("timestampDate") as MaxTimestamp
#             FROM {TABLE_NAME} GROUP BY "stationId"
#         ) t2 ON t1."stationId" = t2."stationId" AND t1."timestampDate" = t2.MaxTimestamp
#         """
#         latest_df = read_sql(query)
#         latest_df['stationId'] = latest_df['stationId'].astype(int)
#     except Exception as e:
#         print(f"ERROR fetching latest station data: {e}")
#         return jsonify({"error": "Failed to fetch station data."}), 500

#     if latest_df.empty:
#         locations_df['quality'] = 'Medium'
#         return jsonify(locations_df.to_dict('records'))

#     classified_qualities = {}
#     for _, row in latest_df.iterrows():
#         station_id = int(row['stationId'])
#         input_data = {feat: row.get(feat, 0) if pd.notna(row.get(feat)) else 0 for feat in classification_features}
#         result = predict_water_quality(input_data)
#         classified_qualities[station_id] = result['class'] if result['status'] == 'success' else 'Medium'

#     locations_df['quality'] = locations_df['stationId'].map(classified_qualities).fillna('Medium')
#     final_list = locations_df[locations_df['stationId'].isin(latest_df['stationId'].unique())].to_dict('records')
#     return jsonify(final_list)


# # ─── Classification ───────────────────────────────────────────────────────────

# @app.route('/api/classify', methods=['POST'])
# def handle_classification():
#     user_input = request.json
#     result = predict_water_quality(user_input)
#     if result['status'] == 'error':
#         return jsonify(result), 400
#     return jsonify(result)


# # ─── Live Data (Latest DB records) ───────────────────────────────────────────

# @app.route('/api/latest-cpcb-data', methods=['GET'])
# def get_latest_db_data():
#     try:
#         locations_df = pd.read_csv(LOCATIONS_CSV_PATH)
#         locations_df = locations_df[['station_id', 'station_name', 'state']].rename(columns={
#             'station_id': 'stationId',
#             'station_name': 'stationName',
#             'state': 'location'
#         })
#         locations_df['stationId'] = locations_df['stationId'].astype(int)
#     except Exception as e:
#         return jsonify({"error": f"Failed to load location data: {e}"}), 500

#     try:
#         query = f"""
#         SELECT t1.* FROM {TABLE_NAME} t1
#         INNER JOIN (
#             SELECT "stationId", MAX("timestampDate") as MaxTimestamp
#             FROM {TABLE_NAME} GROUP BY "stationId"
#         ) t2 ON t1."stationId" = t2."stationId" AND t1."timestampDate" = t2.MaxTimestamp
#         """
#         latest_df = read_sql(query)
#         latest_df['stationId'] = latest_df['stationId'].astype(int)
#         if 'timestampDate' in latest_df.columns:
#             latest_df['timestamp'] = pd.to_datetime(latest_df['timestampDate']).dt.strftime('%Y-%m-%d %H:%M:%S')
#     except Exception as e:
#         return jsonify({"error": f"Failed to fetch data from database: {e}"}), 500

#     if latest_df.empty:
#         return jsonify({"data": [], "last_fetched": datetime.now().isoformat()})

#     try:
#         merged_df = pd.merge(latest_df, locations_df, on='stationId', how='left')
#         non_param_cols = ['stationId', 'stationName', 'location', 'timestamp', 'timestampDate', 'id']
#         param_cols = [col for col in merged_df.columns if col not in non_param_cols]
#         final_cols = ['stationId', 'stationName', 'location', 'timestamp'] + sorted(param_cols)
#         final_cols = [c for c in final_cols if c in merged_df.columns]
#         data_list = merged_df[final_cols].to_dict('records')
#         return jsonify({"data": data_list, "last_fetched": datetime.now().isoformat()})
#     except Exception as e:
#         return jsonify({"error": f"Failed to process data: {e}"}), 500


# # ─── Prediction Endpoints ─────────────────────────────────────────────────────

# @app.route('/api/predictions/daily/<station_id>', methods=['GET'])
# def get_daily_prediction(station_id):
#     data, err = read_json_file(os.path.join(DAILY_PRED_DIR, f"daily_pred_station_{station_id}.json"))
#     if err:
#         return jsonify({"error": "Prediction not found for this station."}), 404
#     return jsonify(data)

# @app.route('/api/predictions/weekly/<station_id>', methods=['GET'])
# def get_weekly_prediction(station_id):
#     data, err = read_json_file(os.path.join(WEEKLY_PRED_DIR, f"weekly_pred_station_{station_id}.json"))
#     if err:
#         return jsonify({"error": "Prediction not found for this station."}), 404
#     return jsonify(data)

# @app.route('/api/predictions/weekly_details/<station_id>', methods=['GET'])
# def get_weekly_details(station_id):
#     data, err = read_json_file(os.path.join(WEEKLY_DETAILS_DIR, f"weekly_details_station_{station_id}.json"))
#     if err:
#         return jsonify({"error": "Weekly details not found for this station."}), 404
#     return jsonify(data)

# @app.route('/api/predictions/summary/daily', methods=['GET'])
# def get_daily_summary():
#     data, err = read_json_file(DAILY_SUMMARY_PATH)
#     if err:
#         return jsonify({"error": "Daily summary not found. Run batch jobs first."}), 404
#     return jsonify(data)

# @app.route('/api/predictions/summary/weekly', methods=['GET'])
# def get_weekly_summary():
#     data, err = read_json_file(WEEKLY_SUMMARY_PATH)
#     if err:
#         return jsonify({"error": "Weekly summary not found. Run batch jobs first."}), 404
#     return jsonify(data)


# # ─── Analysis Endpoints ───────────────────────────────────────────────────────

# @app.route('/api/anomaly-heatmap', methods=['GET'])
# def get_anomaly_map():
#     data, err = read_json_file(ANOMALY_PLOT_PATH)
#     if err:
#         return jsonify({"error": "Anomaly heatmap not found. Run batch jobs first."}), 404
#     return jsonify(data)

# @app.route('/api/correlation/<station_id>', methods=['GET'])
# def get_correlation_plot(station_id):
#     method = request.args.get('method', 'spearman').lower()
#     if method not in ['pearson', 'spearman', 'kendall']:
#         method = 'spearman'
#     data, err = read_json_file(os.path.join(CORRELATION_DIR, f"correlation_station_{station_id}_{method}.json"))
#     if err:
#         return jsonify({"error": f"Correlation plot ({method}) not found for station {station_id}."}), 404
#     return jsonify(data)

# @app.route('/api/daynight/list', methods=['GET'])
# def list_daynight_plots():
#     try:
#         files = [f for f in os.listdir(DAYNIGHT_DIR) if f.endswith(".png")]
#         return jsonify(files)
#     except FileNotFoundError:
#         return jsonify({"error": "Day/Night plot directory not found."}), 404
#     except Exception as e:
#         return jsonify({"error": f"Failed to list files: {e}"}), 500


# # ─── Start App ────────────────────────────────────────────────────────────────

# if __name__ == '__main__':
#     db_type = 'Supabase (PostgreSQL)' if DATABASE_URL else 'Local SQLite'
#     print(f"Starting AquaMetrics backend — DB: {db_type}")
#     app.run(debug=True, port=5000, use_reloader=False)




# backend/main.py
from flask import Flask, request, jsonify
from flask_cors import CORS
from flask_compress import Compress
import json
import os
import pandas as pd
from datetime import datetime

BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))

# Paths
LOCATIONS_CSV_PATH   = os.path.join(BACKEND_DIR, "data/cpcb_station_locations.csv")
STATIC_DIR           = os.path.join(BACKEND_DIR, "static")
DAILY_PRED_DIR       = os.path.join(STATIC_DIR, "predictions/daily")
WEEKLY_PRED_DIR      = os.path.join(STATIC_DIR, "predictions/weekly")
DAYNIGHT_DIR         = os.path.join(STATIC_DIR, "daynight")
ANOMALY_PLOT_PATH    = os.path.join(STATIC_DIR, "anomaly/anomaly_heatmap.json")
CORRELATION_DIR      = os.path.join(STATIC_DIR, "correlation")
WEEKLY_DETAILS_DIR   = os.path.join(STATIC_DIR, "predictions/weekly_details")
DAILY_SUMMARY_PATH   = os.path.join(STATIC_DIR, "predictions/daily_summary_predictions.json")
WEEKLY_SUMMARY_PATH  = os.path.join(STATIC_DIR, "predictions/weekly_summary_predictions.json")
STATION_QUALITY_PATH = os.path.join(STATIC_DIR, "station_quality.json")

TABLE_NAME = "water_records"

# ── Flask app ──────────────────────────────────────────────────────────────────
app = Flask(__name__, static_folder=STATIC_DIR)
CORS(app)        # fully open — allows all origins
Compress(app)    # gzip compression

# ── Load heavy dependencies safely (won't crash server if missing) ─────────────
try:
    from models.classification import predict_water_quality, features as classification_features
    CLASSIFICATION_AVAILABLE = True
    print("✅ Classification model loaded.")
except Exception as e:
    print(f"⚠️  Classification model NOT loaded: {e}")
    CLASSIFICATION_AVAILABLE = False
    classification_features = []
    def predict_water_quality(x):
        return {"status": "error", "message": "Model not available"}

try:
    from db import read_sql, DATABASE_URL
    DB_AVAILABLE = True
    print(f"✅ DB helper loaded. Using: {'Supabase' if DATABASE_URL else 'SQLite'}")
except Exception as e:
    print(f"⚠️  DB helper NOT loaded: {e}")
    DB_AVAILABLE = False
    DATABASE_URL = None
    def read_sql(q, params=None):
        raise RuntimeError("DB not available")


# ── Helper ─────────────────────────────────────────────────────────────────────
def read_json_file(path):
    if not os.path.exists(path):
        return None, f"File not found: {path}"
    try:
        with open(path, 'r') as f:
            return json.load(f), None
    except Exception as e:
        return None, str(e)


# ── Health check ───────────────────────────────────────────────────────────────
@app.route('/', methods=['GET', 'HEAD'])
def health_check():
    return jsonify({
        "status": "ok",
        "db": "supabase" if DATABASE_URL else "sqlite",
        "classification": CLASSIFICATION_AVAILABLE,
        "db_available": DB_AVAILABLE,
    })

@app.route('/api/health', methods=['GET'])
def api_health():
    return jsonify({"status": "ok"})

@app.route('/api/debug-db', methods=['GET'])
def debug_db():
    try:
        # Get column names and first 2 rows
        df = read_sql("SELECT * FROM water_records LIMIT 2")
        return jsonify({
            "columns": list(df.columns),
            "row_count_sample": len(df),
            "first_row": df.iloc[0].to_dict() if len(df) > 0 else {}
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ── Stations ───────────────────────────────────────────────────────────────────
@app.route('/api/stations', methods=['GET'])
def get_stations():
    # Load location CSV
    try:
        locations_df = pd.read_csv(LOCATIONS_CSV_PATH)
        locations_df = locations_df[
            ['station_id', 'station_name', 'latitude', 'longitude', 'state']
        ].rename(columns={
            'station_id':   'stationId',
            'station_name': 'name',
            'latitude':     'lat',
            'longitude':    'lng',
            'state':        'location'
        })
        locations_df['stationId'] = pd.to_numeric(
            locations_df['stationId'], errors='coerce'
        ).dropna().astype(int)
    except Exception as e:
        print(f"ERROR loading locations CSV: {e}")
        return jsonify({"error": f"Failed to load station location data: {e}"}), 500

    # Fast path — pre-computed quality file
    if os.path.exists(STATION_QUALITY_PATH):
        try:
            with open(STATION_QUALITY_PATH, 'r') as f:
                quality_map = json.load(f)
            locations_df['quality'] = (
                locations_df['stationId'].astype(str).map(quality_map).fillna('Medium')
            )
            print(f"✅ Returning {len(locations_df)} stations from quality file.")
            return jsonify(locations_df.to_dict('records'))
        except Exception as e:
            print(f"Warning: quality file failed: {e}")

    # Fallback — assign Medium to all (avoids slow DB call / timeout)
    locations_df['quality'] = 'Medium'
    print(f"⚠️  No quality file — returning {len(locations_df)} stations with Medium quality.")
    return jsonify(locations_df.to_dict('records'))


# ── Classification ─────────────────────────────────────────────────────────────
@app.route('/api/classify', methods=['POST'])
def handle_classification():
    if not CLASSIFICATION_AVAILABLE:
        return jsonify({"status": "error", "message": "Classification model not loaded."}), 503
    try:
        user_input = request.json
        result = predict_water_quality(user_input)
        if result['status'] == 'error':
            return jsonify(result), 400
        return jsonify(result)
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ── Latest DB data ─────────────────────────────────────────────────────────────
@app.route('/api/latest-cpcb-data', methods=['GET'])
def get_latest_db_data():
    if not DB_AVAILABLE:
        return jsonify({"error": "Database not available on server."}), 503

    try:
        locations_df = pd.read_csv(LOCATIONS_CSV_PATH)
        locations_df = locations_df[['station_id', 'station_name', 'state']].rename(columns={
            'station_id':   'stationId',
            'station_name': 'stationName',
            'state':        'location'
        })
        locations_df['stationId'] = pd.to_numeric(
            locations_df['stationId'], errors='coerce'
        ).astype('Int64')
    except Exception as e:
        return jsonify({"error": f"Failed to load location data: {e}"}), 500

    try:
        query = """
        SELECT t1.* FROM water_records t1
        INNER JOIN (
            SELECT "stationId", MAX("timestampDate") as MaxTimestamp
            FROM water_records GROUP BY "stationId"
        ) t2 ON t1."stationId" = t2."stationId"
           AND t1."timestampDate" = t2.MaxTimestamp
        """
        latest_df = read_sql(query)
        latest_df['stationId'] = pd.to_numeric(
            latest_df['stationId'], errors='coerce'
        ).astype('Int64')
        if 'timestampDate' in latest_df.columns:
            latest_df['timestamp'] = (
                pd.to_datetime(latest_df['timestampDate'], errors='coerce')
                  .dt.strftime('%Y-%m-%d %H:%M:%S')
            )
    except Exception as e:
        print(f"ERROR fetching DB data: {e}")
        return jsonify({"error": f"Failed to fetch data from database: {e}"}), 500

    if latest_df.empty:
        return jsonify({"data": [], "last_fetched": datetime.now().isoformat()})

    try:
        merged_df = pd.merge(latest_df, locations_df, on='stationId', how='left')
        non_param = {'stationId', 'stationName', 'location', 'timestamp', 'timestampDate', 'id'}
        param_cols = sorted([c for c in merged_df.columns if c not in non_param])
        ordered = ['stationId', 'stationName', 'location', 'timestamp'] + param_cols
        ordered = [c for c in ordered if c in merged_df.columns]
        data_list = (
            merged_df[ordered]
            .where(pd.notnull(merged_df[ordered]), None)
            .to_dict('records')
        )
        return jsonify({"data": data_list, "last_fetched": datetime.now().isoformat()})
    except Exception as e:
        return jsonify({"error": f"Failed to process data: {e}"}), 500


# ── Prediction endpoints ───────────────────────────────────────────────────────
@app.route('/api/predictions/daily/<station_id>', methods=['GET'])
def get_daily_prediction(station_id):
    data, err = read_json_file(
        os.path.join(DAILY_PRED_DIR, f"daily_pred_station_{station_id}.json")
    )
    if err: return jsonify({"error": "Prediction not found for this station."}), 404
    return jsonify(data)

@app.route('/api/predictions/weekly/<station_id>', methods=['GET'])
def get_weekly_prediction(station_id):
    data, err = read_json_file(
        os.path.join(WEEKLY_PRED_DIR, f"weekly_pred_station_{station_id}.json")
    )
    if err: return jsonify({"error": "Prediction not found for this station."}), 404
    return jsonify(data)

@app.route('/api/predictions/weekly_details/<station_id>', methods=['GET'])
def get_weekly_details(station_id):
    data, err = read_json_file(
        os.path.join(WEEKLY_DETAILS_DIR, f"weekly_details_station_{station_id}.json")
    )
    if err: return jsonify({"error": "Weekly details not found for this station."}), 404
    return jsonify(data)

@app.route('/api/predictions/summary/daily', methods=['GET'])
def get_daily_summary():
    data, err = read_json_file(DAILY_SUMMARY_PATH)
    if err: return jsonify({"error": "Daily summary not found. Run batch jobs first."}), 404
    return jsonify(data)

@app.route('/api/predictions/summary/weekly', methods=['GET'])
def get_weekly_summary():
    data, err = read_json_file(WEEKLY_SUMMARY_PATH)
    if err: return jsonify({"error": "Weekly summary not found. Run batch jobs first."}), 404
    return jsonify(data)


# ── Analysis endpoints ─────────────────────────────────────────────────────────
@app.route('/api/anomaly-heatmap', methods=['GET'])
def get_anomaly_map():
    data, err = read_json_file(ANOMALY_PLOT_PATH)
    if err: return jsonify({"error": "Anomaly heatmap not found. Run batch jobs first."}), 404
    return jsonify(data)

@app.route('/api/correlation/<station_id>', methods=['GET'])
def get_correlation_plot(station_id):
    method = request.args.get('method', 'spearman').lower()
    if method not in ['pearson', 'spearman', 'kendall']:
        method = 'spearman'
    data, err = read_json_file(
        os.path.join(CORRELATION_DIR, f"correlation_station_{station_id}_{method}.json")
    )
    if err:
        return jsonify({"error": f"Correlation plot not found for station {station_id}."}), 404
    return jsonify(data)

@app.route('/api/daynight/list', methods=['GET'])
def list_daynight_plots():
    try:
        if not os.path.exists(DAYNIGHT_DIR):
            return jsonify([])
        files = [f for f in os.listdir(DAYNIGHT_DIR) if f.endswith(".png")]
        return jsonify(files)
    except Exception as e:
        return jsonify({"error": f"Failed to list files: {e}"}), 500


# ── Run ────────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    app.run(debug=True, port=5000, use_reloader=False)
